version: '3.7'
services:
  postgres:
    image: postgres:12.2
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=passwordforpostgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@email.com
      - PGADMIN_DEFAULT_PASSWORD=passwordforpgadmin
    ports:
      - '8082:80'
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
